### PR TITLE
Adding extra Tags for Format and Stream. Adding FieldOrder field to S…

### PR DESCRIPTION
**Pull request by agorman**
…tream

Thanks for the awesome package. There are a few extra fields I'd like to be able to pull. Let me know if you see any issues.

Thanks!

### CODE REVIEW

**Comment by vansante** [comment]
I am starting to regret adding Tags as a struct instead of a `map[string]string` as this will probably end up as an ever growing struct with all formats and streams adding new identifiers :thinking:. (just looking [here](https://developer.apple.com/library/archive/documentation/QuickTime/QTFF/Metadata/Metadata.html) makes me think a lot could be added :fearful: )

I may have a look at trying to add that without breaking compatibility.

The FieldOrder should be fine though.

**Comment by vansante** [comment]
I just merged #32 to the `v2` branch, can you try using the new tags map API to retrieve your tags?

If that works, can you update this PR to just add the FieldOrder field, then I can merge it and we can tag a new version afterwards.

Thanks! :smile:

**Comment by agorman** [comment]
I think a `map[string]string` is a great idea. Thanks!

**Comment by vansante** [comment]
There are still conflicts, can you rebase your changes on `v2` ? :)

**Pull request closed without merging**
